backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "المشاريع"
    folder: "content/projects"
    create: true
    fields:
      - {label: "عنوان المشروع", name: "title", widget: "string"}
      - {label: "صورة العمل", name: "image", widget: "image"}
      - {label: "وصف بسيط", name: "body", widget: "markdown"}
      
