backend:
  name: github
  repo: yassine060793/NYK---Construction
  branch: main
  # الآن نستخدم رابط موقعك الحقيقي على Vercel
  base_url: https://nyk-construction.vercel.app
  auth_endpoint: /api/auth

