backend:
  name: github
  repo: yassine060793/NYK---Construction
  branch: main
  base_url: https://external-auth-gate.vercel.app
  

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "projects"
    label: "معرض مشاريعنا"
    folder: "_posts/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "عنوان المشروع", name: "title", widget: "string" }
      - { label: "تاريخ العمل", name: "date", widget: "datetime" }
      - { label: "الصورة الرئيسية", name: "featured_image", widget: "image" }
      - { label: "وصف الصورة/العمل", name: "image_desc", widget: "string" }
      - { label: "نوع الخدمة", name: "category", widget: "select", options: ["رخام وجرانيت", "تلبيس جدران", "أرضيات كبيرة", "درج وسلالم", "فينيسيون عامة"] }
      - { label: "تفاصيل المشروع الكاملة", name: "body", widget: "markdown" }
