backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "news"
    label: "التحديثات اليومية"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "صورة النوع", name: "image", widget: "image"}
      - {label: "وصف الرخام والشرح", name: "body", widget: "markdown"}
